[snowflake]
user = ""
password = ""
account = ""
warehouse = ""
database = ""
schema = ""

[datarobot]
API_HOST = ""  # noqa
API_KEY = ""
DATAROBOT_KEY = ""
DEPLOYMENT_ID_SMRY = ""
DEPLOYMENT_ID_TRANS = ""

[others]
table = ""